baseURL: "https://rafael.victortoso.com"
theme: "up-business-theme"
languageCode: "pt-br"

title: "Rafael Toso"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Rafael Toso"
  description: "Mais um texto aqui, de fechamento."
  images: 
    - "images/rafael_profile.jpg"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:

  location:
    - "Parque Nacional da Tijuca - Alto da Boa Vista, Rio de Janeiro - RJ, Brazil"

  contact:
    - "contato@rafaeltoso.com"
    - "(+55) 999 888 777"

  copyright: "© 2023 Rafael Toso - Todos os direitos reservados"

  postProcess: false

menus:
  buttons:
    - name: "Entre em contato!"
      url: "https://api.whatsapp.com/send/?phone=%2B55999888777&text&type=phone_number&app_absent=0"
      weight: 5
      pre: "btn btn-primary text-light"

taxonomies:
  series: "series"
  tags: "tags"
